server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;
    location /media/ {
        alias /app/shared/volumes/;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
